spring:
  data:
    redis:
      port: 6379  # Redis服务器端口
      host: 127.0.0.1  # Redis 服务器地址
      database: 0 #redis数据库的索引，默认为0，总共10个
      password:    # redis 服务器密码，默认为空
      lettuce:
        pool:
          min-idle: 10 # 连接池中的最小空闲连接,默认为0
          max-idle: 20 # 连接池中的最大空闲连接,默认为8
          max-active: 100 # 连接池的最大连接数，默认为 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lfy31678

fyl:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018ef1824a3666c8
      accountToken: fa20cedddc7b4f7aaceb816e1167e227
      appId: 2c94811c8cd4da0a018ef1824bc666cf
      templateId: 1

# 配置 MP 框架⽇志级别
logging:
  level:
   com.baomidou.mybatisplus.samples: debug

# MP 配置
mybatis-plus:
   configuration:
    map-underscore-to-camel-case: true # 驼峰下划线转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

   global-config:
     db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


  # springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
     path: /v3/api-docs
  group-configs:
      - group: 'default'
        paths-to-match: '/**'
        # 扫描 controller 包的路径，⾃⾏修改
        packages-to-scan: top.fyl.springboot.redis.controller


# knife4j
knife4j:
   enable: true
   setting:
    language: zh_cn
   basic:
    enable: true
    username: admin
    password: 123456