spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lfy31678
    driver-class-name: com.mysql.cj.jdbc.Driver
#  profiles:
#    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.fyl.zhihu.api.entity
  configuration:
    map-underscore-to-camel-case: true